trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - script: echo "Bonjour Azure Pipeline"
    displayName: "Mon premier script"

  - script: |
      echo "Compilation..."
      echo "Fin"
    displayName: "Build"