resources:
- deployment.yaml
- service.yaml
- sec-secret.yaml
- security-configmap.yaml
images:
- name: brahimbtf/security-service
  newTag: "1.1"
- name: abdelilahxr/security-service
  newTag: "1.0"
